name: Kernel Rebase

on:
  workflow_dispatch:

jobs:
  kernel-rebase:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /home/runner

    steps:

      - uses: actions/checkout@v4

      - name: Import GPG (GnuPG) key 🚚
        uses: crazy-max/ghaction-import-gpg@v6.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          trust_level: 5

      - name: Import SSH (openssh) key 🚚
        run: |
          cd ~
          git clone https://"$GH_PAT"@github.com/techdiwas/ssh-and-gpg-keys.git $HOME/tmp
          mkdir -p $HOME/.ssh
          if [ -f $HOME/tmp/id_rsa ] && [ -f $HOME/tmp/id_rsa.pub ]; then
              mv $HOME/tmp/id_rsa $HOME/mv/id_rsa.pub $HOME/.ssh
              chmod 600 ~/.ssh/id_rsa
              echo "-- SSH key restored."
              eval "$(ssh-agent -s)"
              ssh-add ~/.ssh/id_rsa
          elif [ -f $HOME/tmp/id_ed25519 ] && [ -f $HOME/tmp/id_ed25519.pub ]; then
              mv $HOME/tmp/id_ed25519 $HOME/tmp/id_ed25519.pub $HOME/.ssh
              chmod 600 ~/.ssh/id_ed25519
              echo "-- SSH key restored."
              eval "$(ssh-agent -s)"
              ssh-add ~/.ssh/id_ed25519
          else
              echo "-- No SSH key backup found."
          fi
          rm -rf $HOME/tmp
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USERNAME"
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL}}
          USERNAME: ${{ secrets.USERNAME }}
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Clone script 📜
        run: |
          cd ~
          curl -L -O https://raw.githubusercontent.com/redmi-mt6765-dev/kernel_rebase_action/refs/heads/main/kernel_rebase.sh

      - name: Run script 🚀
        run: |
          cd ~
          bash kernel_rebase.sh "https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git" "dandelion-q-oss" "deprecated/android-4.9-q"
